#==============================================================================
# FILE:          legend.sh
# AUTOHR:        <Firstname, Lastname>
# DATE:          20XX-XX-XX
# PURPOSE:       Bash Script Component for the App Legend
# NOTE:          Legend was generated by using - 
#                https://patorjk.com/software/taag/#p=display&f=Slant&t=demoapp
#==============================================================================

##-----------------------------------------------
## CONFIG(s)
##-----------------------------------------------
APP_LEGEND=$'   __                                       __  _     \n'
APP_LEGEND+=$'  / /____  ______________ _____ ___  ____ _/ /_(_)____\n'
APP_LEGEND+=$' / __/ _ \/ ___/ ___/ __ `/ __ `__ \/ __ `/ __/ / ___/\n'
APP_LEGEND+=$'/ /_/  __/ /  / /  / /_/ / / / / / / /_/ / /_/ / /__  \n'
APP_LEGEND+=$'\__/\___/_/  /_/   \__,_/_/ /_/ /_/\__,_/\__/_/\___/ \n'
export APP_LEGEND

show_legend() {
  echo "$APP_LEGEND"
  echo "----------"
  echo "v$(git describe --tags `git rev-list --tags --max-count=1`)"
  echo ""
}