#==============================================================================
# FILE:          legend.sh
# AUTOHR:        <Firstname, Lastname>
# DATE:          20XX-XX-XX
# PURPOSE:       Bash Script Component for the App Legend
# NOTE:          Legend was generated by using - 
#                https://patorjk.com/software/taag/#p=display&f=Slant&t=demoapp
#==============================================================================

##-----------------------------------------------
## CONFIG(s)
##-----------------------------------------------
APP_LEGEND=$'       __                                     \n'
APP_LEGEND+=$'  ____/ /__  ____ ___  ____  ____ _____  ____ \n'
APP_LEGEND+=$' / __  / _ \/ __ `__ \/ __ \/ __ `/ __ \/ __ \\\n'
APP_LEGEND+=$'/ /_/ /  __/ / / / / / /_/ / /_/ / /_/ / /_/ /\n'
APP_LEGEND+=$'\__,_/\___/_/ /_/ /_/\____/\__,_/ .___/ .___/ \n'
APP_LEGEND+=$'                               /_/   /_/      '
export APP_LEGEND

show_legend() {
  echo "$APP_LEGEND"
  echo "----------"
  echo "v$(git describe --tags `git rev-list --tags --max-count=1`)"
  echo ""
}